---
telemetry:
  enabled: true
  debug: true
  traces:
    endpoint: "192.168.0.152:4317"
  metrics:
    endpoint: "192.168.0.152:4317"
  logs:
    endpoint: "192.168.0.152:4317"
db:
  host: "localhost"
  port: 5432
  name: postgres
ollama:
  endpoint: http://192.168.0.185:11434
  embedding:
    model: nomic-embed-text
    chunk_size: 2000
    chunk_overlap: 300
  generation:
    model: llama3:8b-instruct-q4_K_M
    cache:
      enabled: true
      similarity_threshold: 0.9
    context:
      max_documents: 5
      min_similarity_score: 0.9
      enable: false
