-- Preencha o parâmetro :transaction_id (mesmo valor será usado para correlation_id e transaction_id)
select
    t.transaction_id,
    t.acquirer,
    t.company_id,
    t.workspace_id,
    t.application_id,
    t.application_name,
    t.raw_application_id,
    t.merchant_id,
    t.pos,
    t.type,
    t.amount,
    t.currency,
    t.installments,
    t.recurrent,
    t.soft_descriptor,
    t.status,
    t.payment_id,
    t.authorization_code,
    t.nsu,
    t.response_code,
    t.tokenized,
    t.tid,
    t.date_timestamp,
    t.dt,
    t.refund_amount,
    t.cavv,
    t.eci,
    t.reference_id,
    t.retry_after,
    t.document_type,
    t.document_origin,
    t.has_customer_information,
    t.is_full_refunded,
    t.is_waiting_confirmation,
    t.is_authenticated,
    t.is_data_only,
    t.is_denied,
    t.is_acquirer_fallback,
    t.is_payment_method_fallback,
    t.is_digital_wallet,
    t.digital_wallet_type,
    t.has_updated_card,
    t.fallback_reason,
    t.ip_address,
    t.contains_error,
    t.card_on_file_used,
    t.card_token,
    t.card_hash,
    t.brand_card_token,
    t.card_brand,
    t.card_exp_date,
    t.card_holder,
    t.card_type,
    t.card_pan_id,
    t.entry_mode_origin,
    t.card_bin,
    t.card_last,
    t.cvv_informed,
    t.is_click_to_pay,
    t.click_to_pay_token,
    t.click_to_pay_brand,
    t.click_to_pay_holder,
    t.click_to_pay_exp_date,
    t.click_to_pay_account_reference,
    t.click_to_pay_dynamic_data_value,
    t.partner_account_id,
    t.correlation_id,
    t.trace_id,
    t.error_code,
    null as error_status_code,
    null as error_status,
    null as error_type,
    t.error_operation,
    null as error_message,
    t.transaction_date
from refined_payments.cardpay_transactions t
where t.correlation_id = :transaction_id
   or t.transaction_id = :transaction_id

union all

select
    e.transaction_id,
    e.acquirer,
    e.company_id,
    e.workspace_id,
    e.application_id,
    e.application_name,
    e.raw_application_id,
    e.merchant_id,
    e.pos,
    e.type,
    e.amount,
    e.currency,
    e.installments,
    e.recurrent,
    e.soft_descriptor,
    e.status,
    e.payment_id,
    e.authorization_code,
    e.nsu,
    e.response_code,
    e.tokenized,
    e.tid,
    e.date_timestamp,
    e.dt,
    e.refund_amount,
    e.cavv,
    e.eci,
    e.reference_id,
    e.retry_after,
    e.document_type,
    e.document_origin,
    e.has_customer_information,
    e.is_full_refunded,
    e.is_waiting_confirmation,
    e.is_authenticated,
    e.is_data_only,
    e.is_denied,
    e.is_acquirer_fallback,
    e.is_payment_method_fallback,
    e.is_digital_wallet,
    e.digital_wallet_type,
    e.has_updated_card,
    e.fallback_reason,
    e.ip_address,
    e.contains_error,
    e.card_on_file_used,
    e.card_token,
    e.card_hash,
    e.brand_card_token,
    e.card_brand,
    e.card_exp_date,
    e.card_holder,
    e.card_type,
    e.card_pan_id,
    e.entry_mode_origin,
    e.card_bin,
    e.card_last,
    e.cvv_informed,
    e.is_click_to_pay,
    e.click_to_pay_token,
    e.click_to_pay_brand,
    e.click_to_pay_holder,
    e.click_to_pay_exp_date,
    e.click_to_pay_account_reference,
    e.click_to_pay_dynamic_data_value,
    null as partner_account_id,
    e.correlation_id,
    e.trace_id,
    null as error_code,
    e.error_status_code,
    e.error_status,
    e.error_type,
    e.error_operation,
    e.error_message,
    e.transaction_date
from refined_payments.cardpay_transactions_error e
where e.correlation_id = :transaction_id
   or e.transaction_id = :transaction_id
